name: get_release

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get latest draft
        id: get_latest_draft
        uses: mpaulweeks/get-latest-draft@v0.7
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish the draft
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_id: ${{ steps.get_latest_draft.outputs.id }}
